ERROR:root:Unequal number of 8 and 9 error: uploads/3803SK82Slp.01.csv
ERROR:root:Issue occured in spn: 1
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/home/pwm4/anaconda2/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/home/pwm4/anaconda2/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/home/pwm4/anaconda2/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/home/pwm4/anaconda2/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/home/pwm4/anaconda2/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/home/pwm4/anaconda2/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/home/pwm4/anaconda2/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/home/pwm4/anaconda2/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/home/pwm4/anaconda2/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
